# Generated by Django 5.1.5 on 2025-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_articulo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
